"""Structure, budget, reference and example rules for the five library skills.

Spec: openspec capability ``library-skill-structure`` (change
``restructure-library-skills``). Checks the canonical ``skills/rf-<key>/``
tree; the plugin and VS Code copies are generated by ``scripts/sync-skills.sh``
and compared by ``scripts/check-drift.sh`` (only the catalog-file absence is
checked here for every channel).

Keyword existence in fenced ```robotframework blocks, references and examples
is enforced by ``scripts/check-skill-keywords.py`` (``tests/test_skill_keywords.py``
runs it over the real tree); this module adds the same libdoc check for the
keywords named in the ``Which keyword for which situation`` table, which the
checker does not see because they are inline code in a Markdown table.
"""

from __future__ import annotations

import importlib.util
import re
import subprocess
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parent.parent
CHECKER_SCRIPT = ROOT / "scripts" / "check-skill-keywords.py"

# Skill key -> libdoc import name (also the module probed for the dry-run test).
LIBRARIES: dict[str, str] = {
    "browser": "Browser",
    "selenium": "SeleniumLibrary",
    "appium": "AppiumLibrary",
    "requests": "RequestsLibrary",
    "restinstance": "REST",
}
KEYS = list(LIBRARIES)
SKILL_DIRS = {k: ROOT / "skills" / f"rf-{k}" for k in KEYS}

# Skills not yet restructured: their cases are xfails (non-strict: some rules, such as the
# example dry run, already hold for the old content). Emptied as each skill is done.
PENDING: set[str] = set()


def _param(key: str, *values: object, id: str | None = None):
    marks = [pytest.mark.xfail(strict=False, reason=f"rf-{key} not restructured yet")] if key in PENDING else []
    return pytest.param(*(values or (key,)), id=id or key, marks=marks)


KEY_PARAMS = [_param(k) for k in KEYS]

# Script-based fallback skills named next to the robotcode commands (design D3).
LIBDOC_FALLBACK = "rf-libdoc"
RESULTS_FALLBACK = "rf-results"

REQUIRED_SECTIONS = [
    "Installation",
    "Import and defaults",
    "Which keyword for which situation",
    "Agent workflow",
    "Gotchas",
    "When to read the references",
    "Companion Skills",
]
# Optional sections may only sit between these two required ones.
OPTIONAL_AFTER, OPTIONAL_BEFORE = "Which keyword for which situation", "Gotchas"
# The trigger block (skill-triggering, tune-skill-descriptions D12) sits right
# after the orientation, before "Installation", within the first 20 body lines.
LEADING_SECTION = "When to use"

MAX_LINES = 250
MAX_CHARS = 12_000
MAX_ORIENTATION_LINES = 6  # ~5 lines of orientation + the "Verified against" line
TOC_WINDOW = 15
TOC_THRESHOLD = 100

SHOUT_WORDS = {
    "NEVER", "ALWAYS", "MUST", "CRITICAL", "IMPORTANT", "WARNING", "NOTE",
    "DO", "DON'T", "NOT", "SHOULD", "REQUIRED",
}
DATED_RE = re.compile(
    r"\bas of\b|\brecently\b|\bnew in\b|\bcurrently\b|"
    r"\b(January|February|March|April|May|June|July|August|September|October|November|December)\s+\d{4}\b",
    re.I,
)
LEGACY_RE = re.compile(r"Run Keyword (?:If|Unless)(?=\s{2,}|\t|$)|\bExit For Loop\b|\[Return\]", re.I)
INSTALL_RE = re.compile(r"\bpip3? install\b|\buv add\b|\bnpm install\b|\bnpm i\b")
REF_LINK_RE = re.compile(r"references/([\w.-]+\.md)")
FENCE_RE = re.compile(r"^\s*```")
ROBOT_FENCE_RE = re.compile(r"^\s*```\s*(robotframework|robot)\s*$", re.I)

# Inline-code cells in the decision table that are settings or syntax, not keywords.
NOT_KEYWORDS = {
    "suite setup", "suite teardown", "test setup", "test teardown", "test template",
    "library", "resource", "variables", "test tags", "keyword tags",
}


# --- helpers ---------------------------------------------------------------


def skill_md(key: str) -> str:
    return (SKILL_DIRS[key] / "SKILL.md").read_text(encoding="utf-8")


def body_of(text: str) -> str:
    """SKILL.md without its YAML frontmatter."""
    if text.startswith("---"):
        end = text.find("\n---", 3)
        return text[end + 4:] if end != -1 else text
    return text


def h2_headings(text: str) -> list[str]:
    out, in_fence = [], False
    for line in text.splitlines():
        if FENCE_RE.match(line):
            in_fence = not in_fence
            continue
        if not in_fence and line.startswith("## "):
            out.append(line[3:].strip())
    return out


def section(text: str, heading: str) -> str:
    m = re.search(rf"^## {re.escape(heading)}[ \t]*\n(.*?)(?=^## |\Z)", text, re.M | re.S)
    return m.group(1) if m else ""


def prose_lines(text: str) -> list[tuple[int, str]]:
    """(line number, line) outside fenced code, with inline code removed."""
    out, in_fence = [], False
    for no, line in enumerate(text.splitlines(), 1):
        if FENCE_RE.match(line):
            in_fence = not in_fence
            continue
        if not in_fence:
            out.append((no, re.sub(r"`[^`]*`", "", line)))
    return out


def robot_blocks(text: str) -> list[list[str]]:
    blocks, cur, inside = [], [], False
    for line in text.splitlines():
        if not inside and ROBOT_FENCE_RE.match(line):
            inside, cur = True, []
        elif inside and FENCE_RE.match(line):
            blocks.append(cur)
            inside = False
        elif inside:
            cur.append(line)
    return blocks


def fenced_blocks(text: str) -> list[list[str]]:
    blocks, cur, inside = [], [], False
    for line in text.splitlines():
        if FENCE_RE.match(line):
            if inside:
                blocks.append(cur)
            inside, cur = not inside, []
        elif inside:
            cur.append(line)
    return blocks


def table_rows(text: str) -> list[list[str]]:
    rows = []
    for line in text.splitlines():
        s = line.strip()
        if not s.startswith("|"):
            continue
        cells = [c.strip() for c in s.strip("|").split("|")]
        if all(re.fullmatch(r":?-{2,}:?", c) for c in cells if c):
            continue
        rows.append(cells)
    return rows


def references(key: str) -> list[Path]:
    ref_dir = SKILL_DIRS[key] / "references"
    return sorted(ref_dir.glob("*.md")) if ref_dir.is_dir() else []


def examples(key: str) -> list[Path]:
    ex_dir = SKILL_DIRS[key] / "assets" / "examples"
    return sorted(ex_dir.glob("*.robot")) if ex_dir.is_dir() else []


def slug(heading: str) -> str:
    s = re.sub(r"[^\w\s-]", "", heading.lower()).strip()
    return re.sub(r"\s+", "-", s)


def toc_problems(path: Path) -> list[str]:
    """A contents list must start within the first TOC_WINDOW lines and name every H2."""
    lines = path.read_text(encoding="utf-8").splitlines()
    if len(lines) <= TOC_THRESHOLD:
        return []
    start = next(
        (i for i, ln in enumerate(lines[:TOC_WINDOW]) if re.match(r"\s*(?:[-*]|\d+\.)\s+", ln)), None
    )
    if start is None:
        return [f"{path.name}: {len(lines)} lines but no contents list in the first {TOC_WINDOW} lines"]
    end = start
    while end < len(lines) and re.match(r"\s*(?:[-*]|\d+\.)\s+", lines[end]):
        end += 1
    toc = "\n".join(lines[start:end]).lower()
    missing = [h for h in h2_headings("\n".join(lines)) if h.lower() not in toc and slug(h) not in toc]
    return [f"{path.name}: contents list misses H2 {h!r}" for h in missing]


def decision_table_keywords(text: str) -> list[str]:
    """Keyword-like inline-code spans in the ``Use`` column of the decision table."""
    names = []
    for row in table_rows(section(text, "Which keyword for which situation"))[1:]:
        if len(row) < 2:
            continue
        for span in re.findall(r"`([^`]+)`", row[1]):
            name = re.split(r"\s{2,}|\t", span.strip())[0].strip()
            if not re.fullmatch(r"[A-Z][A-Za-z0-9]*(?: [A-Za-z][A-Za-z0-9]*)+", name):
                continue
            if name.lower() in NOT_KEYWORDS:
                continue
            names.append(name)
    return names


def _load_checker():
    spec = importlib.util.spec_from_file_location("check_skill_keywords_structure", CHECKER_SCRIPT)
    module = importlib.util.module_from_spec(spec)
    sys.modules["check_skill_keywords_structure"] = module
    assert spec.loader is not None
    spec.loader.exec_module(module)
    return module


def keyword_problems(names: list[str], import_name: str) -> list[str]:
    """Names that are unknown or deprecated in the library + standard libraries."""
    pytest.importorskip("robot")
    checker = _load_checker()
    lib = checker.load_library(import_name)
    if lib is None:
        pytest.skip(f"{import_name} is not importable")
    std: dict[str, object] = {}
    for std_name in checker.STANDARD_LIBRARIES:
        info = checker.load_library(std_name)
        if info:
            std.update(info.keywords)
    probs = []
    for name in names:
        norm = checker.normalize(name)
        kw = lib.keywords.get(norm) or std.get(norm)
        if kw is None:
            probs.append(f"UNKNOWN {name}")
        elif kw.deprecated:
            probs.append(f"DEPRECATED {name}")
    return probs


# --- structure -------------------------------------------------------------


@pytest.mark.parametrize("key", KEY_PARAMS)
def test_required_sections_in_order(key):
    heads = h2_headings(body_of(skill_md(key)))
    missing = [h for h in REQUIRED_SECTIONS if h not in heads]
    assert not missing, f"rf-{key}: missing sections {missing}"
    required_order = [h for h in heads if h in REQUIRED_SECTIONS]
    assert required_order == REQUIRED_SECTIONS, f"rf-{key}: section order {required_order}"
    lo, hi = heads.index(OPTIONAL_AFTER), heads.index(OPTIONAL_BEFORE)
    stray = [
        h for i, h in enumerate(heads)
        if h not in REQUIRED_SECTIONS and not lo < i < hi and not (i == 0 and h == LEADING_SECTION)
    ]
    assert not stray, f"rf-{key}: optional sections outside {OPTIONAL_AFTER!r}..{OPTIONAL_BEFORE!r}: {stray}"


@pytest.mark.parametrize("key", KEY_PARAMS)
def test_orientation_is_short_and_has_version_line(key):
    body = body_of(skill_md(key))
    m = re.search(r"^# [^\n]*\n(.*?)(?=^## )", body, re.M | re.S)
    assert m, f"rf-{key}: no H1 title before the first section"
    lines = [ln for ln in m.group(1).splitlines() if ln.strip()]
    assert 1 <= len(lines) <= MAX_ORIENTATION_LINES, f"rf-{key}: orientation has {len(lines)} lines"
    assert any(ln.startswith("Verified against ") for ln in lines), f"rf-{key}: no 'Verified against' line"


@pytest.mark.parametrize("key", KEY_PARAMS)
def test_size_budget(key):
    text = skill_md(key)
    n_lines, n_chars = len(text.splitlines()), len(text)
    assert n_lines <= MAX_LINES, f"rf-{key}: {n_lines} lines > {MAX_LINES}"
    assert n_chars <= MAX_CHARS, f"rf-{key}: {n_chars} chars > {MAX_CHARS}"


@pytest.mark.parametrize("key", KEY_PARAMS)
def test_single_default_import(key):
    body = section(skill_md(key), "Import and defaults")
    assert body, f"rf-{key}: no 'Import and defaults' section"
    imports = [
        ln for block in fenced_blocks(body) for ln in block if re.match(r"^Library\s{2,}\S", ln.strip())
    ]
    assert len(imports) == 1, f"rf-{key}: expected one recommended Library import, got {imports}"
    assert re.match(rf"^Library\s{{2,}}{re.escape(LIBRARIES[key])}(\s|$)", imports[0].strip())
    assert robot_blocks(body), f"rf-{key}: no robotframework open/session example"
    assert "references/" in body, f"rf-{key}: escape hatch does not point to a reference file"


@pytest.mark.parametrize("key", KEY_PARAMS)
def test_install_commands_only_in_installation_section(key):
    text = body_of(skill_md(key))
    install = section(text, "Installation")
    assert "rf-setup" in install
    outside = text.replace(install, "")
    hits = [ln.strip() for ln in outside.splitlines() if INSTALL_RE.search(ln)]
    assert not hits, f"rf-{key}: install commands outside '## Installation': {hits}"


# --- decision table, workflow, gotchas --------------------------------------


@pytest.mark.parametrize("key", KEY_PARAMS)
def test_decision_table_routes_to_existing_references(key):
    body = section(skill_md(key), "Which keyword for which situation")
    rows = table_rows(body)
    assert len(rows) >= 6, f"rf-{key}: decision table has {max(len(rows) - 1, 0)} rows"
    named = set(REF_LINK_RE.findall(body))
    existing = {p.name for p in references(key)}
    assert named <= existing, f"rf-{key}: decision table names missing references {sorted(named - existing)}"


@pytest.mark.parametrize("key", KEY_PARAMS)
def test_decision_table_keywords_exist(key):
    names = decision_table_keywords(skill_md(key))
    assert len(names) >= 5, f"rf-{key}: only {names} recognised as keywords in the decision table"
    probs = keyword_problems(names, LIBRARIES[key])
    assert not probs, f"rf-{key}: decision table keywords: {probs}"


def test_decision_table_checker_flags_planted_keyword():
    text = (
        "## Which keyword for which situation\n\n| Situation | Use | Details |\n|---|---|---|\n"
        "| Wait for items | `Wait Until Element Count Is Greater Than    css:li    3` | — |\n"
        "| Click | `Click Element` | — |\n\n## Agent workflow\n"
    )
    names = decision_table_keywords(text)
    assert names == ["Wait Until Element Count Is Greater Than", "Click Element"]
    assert keyword_problems(names, "SeleniumLibrary") == ["UNKNOWN Wait Until Element Count Is Greater Than"]


@pytest.mark.parametrize("key", KEY_PARAMS)
def test_agent_workflow_loop(key):
    body = section(skill_md(key), "Agent workflow")
    items = re.findall(r"^\d+\.\s+(.*(?:\n(?!\d+\.).*)*)", body, re.M)
    assert len(items) >= 5, f"rf-{key}: workflow has {len(items)} numbered steps"
    flat = body.replace("\n", " ")
    for token in (f"robotcode libdoc {LIBRARIES[key]}", LIBDOC_FALLBACK, "--dryrun", "robotcode results",
                  RESULTS_FALLBACK):
        assert token in flat, f"rf-{key}: workflow lacks {token!r}"
    order = [flat.index("robotcode libdoc"), flat.index("--dryrun"), flat.index("robotcode results")]
    assert order == sorted(order), f"rf-{key}: workflow steps out of order"
    last = items[-1].lower()
    assert "fix" in last and ("dry run" in last or "--dryrun" in last or "step 3" in last), (
        f"rf-{key}: last workflow step does not loop back to the dry run: {items[-1]!r}"
    )


@pytest.mark.parametrize("key", KEY_PARAMS)
def test_gotchas(key):
    body = section(skill_md(key), "Gotchas")
    items = re.findall(r"^- (.*(?:\n(?!- |\n).*)*)", body, re.M)
    assert len(items) >= 5, f"rf-{key}: {len(items)} gotchas (< 5)"
    no_code = [i[:60] for i in items if "`" not in i]
    assert not no_code, f"rf-{key}: gotchas without a named keyword/argument/default: {no_code}"


@pytest.mark.parametrize("key", KEY_PARAMS)
def test_libdoc_instruction_instead_of_catalog(key):
    text = skill_md(key)
    assert f"robotcode libdoc {LIBRARIES[key]} " in text
    assert re.search(rf"robotcode libdoc {re.escape(LIBRARIES[key])} list ", text), f"rf-{key}: no libdoc list example"
    assert re.search(rf"robotcode libdoc {re.escape(LIBRARIES[key])} show ", text), f"rf-{key}: no libdoc show example"
    assert LIBDOC_FALLBACK in text


CHANNEL_PARAMS = [
    pytest.param(
        path, id=name,
        marks=[pytest.mark.xfail(strict=False, reason="catalogs not deleted yet")] if PENDING else [],
    )
    for name, path in (
        ("root", ROOT / "skills"),
        ("plugin", ROOT / "plugins" / "rf-agentskills" / "skills"),
        ("vscode", ROOT / "vscode-extension" / "skills"),
    )
]


@pytest.mark.parametrize("channel", CHANNEL_PARAMS)
def test_no_keyword_catalog_in_any_channel(channel):
    hits = [p for k in KEYS for p in (channel / f"rf-{k}").rglob("keywords-reference.md")]
    assert not hits, f"keyword catalogs still shipped: {hits}"
    linked = [
        f"{p.relative_to(ROOT)}"
        for k in KEYS
        for p in (channel / f"rf-{k}").rglob("*.md")
        if "keywords-reference" in p.read_text(encoding="utf-8")
    ]
    assert not linked, f"links to keywords-reference.md: {linked}"


# --- references ------------------------------------------------------------


@pytest.mark.parametrize("key", KEY_PARAMS)
def test_reference_table_matches_files(key):
    body = section(skill_md(key), "When to read the references")
    rows = table_rows(body)
    assert rows and [c.lower() for c in rows[0][:2]] == ["read", "when"], f"rf-{key}: header {rows[:1]}"
    named = set(REF_LINK_RE.findall(body))
    existing = {p.name for p in references(key)}
    assert named == existing, f"rf-{key}: table-only {sorted(named - existing)}, file-only {sorted(existing - named)}"


@pytest.mark.parametrize("key", KEY_PARAMS)
def test_references_are_one_level_deep(key):
    bad = []
    for ref in references(key):
        text = ref.read_text(encoding="utf-8")
        for no, line in enumerate(text.splitlines(), 1):
            if REF_LINK_RE.search(line) or re.search(r"\]\((?!https?:)[^)]*\.md(#[^)]*)?\)", line):
                bad.append(f"{ref.name}:{no}: {line.strip()}")
    assert not bad, f"rf-{key}: reference-to-reference links:\n" + "\n".join(bad)


@pytest.mark.parametrize("key", KEY_PARAMS)
def test_long_references_have_toc(key):
    probs = [p for ref in references(key) for p in toc_problems(ref)]
    assert not probs, f"rf-{key}:\n" + "\n".join(probs)


# --- style -----------------------------------------------------------------


def _style_files(key: str) -> list[Path]:
    return [SKILL_DIRS[key] / "SKILL.md", *references(key)]


@pytest.mark.parametrize("key", KEY_PARAMS)
def test_verified_line_once(key):
    hits = [
        (p.name, ln)
        for p in _style_files(key)
        for ln in p.read_text(encoding="utf-8").splitlines()
        if "Verified against" in ln
    ]
    assert len(hits) == 1 and hits[0][0] == "SKILL.md", f"rf-{key}: 'Verified against' lines: {hits}"
    assert re.search(r"Verified against .+ \d+\.\d+(\.\d+)?, Robot Framework \d+\.\d+", hits[0][1]), hits[0][1]


@pytest.mark.parametrize("key", KEY_PARAMS)
def test_no_shouting_in_prose(key):
    bad = []
    for path in _style_files(key):
        text = path.read_text(encoding="utf-8")
        if path.name == "SKILL.md":
            text = body_of(text)
        for no, line in prose_lines(text):
            words = set(re.findall(r"\b[A-Z][A-Z']+\b", line))
            loud = sorted(words & SHOUT_WORDS)
            if loud:
                bad.append(f"{path.name}:{no}: {loud}: {line.strip()[:80]}")
    assert not bad, f"rf-{key}: ALL-CAPS emphasis in prose:\n" + "\n".join(bad)


@pytest.mark.parametrize("key", KEY_PARAMS)
def test_no_dated_statements(key):
    bad = []
    for path in _style_files(key):
        for no, line in prose_lines(path.read_text(encoding="utf-8")):
            if "Verified against" not in line and DATED_RE.search(line):
                bad.append(f"{path.name}:{no}: {line.strip()[:80]}")
    assert not bad, f"rf-{key}: time-sensitive statements:\n" + "\n".join(bad)


@pytest.mark.parametrize("key", KEY_PARAMS)
def test_no_legacy_syntax(key):
    bad = []
    for path in _style_files(key):
        for block in robot_blocks(path.read_text(encoding="utf-8")):
            bad += [f"{path.name}: {ln.strip()}" for ln in block if LEGACY_RE.search(ln)]
    for ex in examples(key):
        bad += [f"{ex.name}: {ln.strip()}" for ln in ex.read_text(encoding="utf-8").splitlines() if LEGACY_RE.search(ln)]
    assert not bad, f"rf-{key}: legacy syntax:\n" + "\n".join(bad)


# --- examples --------------------------------------------------------------


@pytest.mark.parametrize("key", KEY_PARAMS)
def test_examples_listed_in_skill_md(key):
    exs = examples(key)
    assert 1 <= len(exs) <= 4, f"rf-{key}: {len(exs)} examples (keep 1-4)"
    text = skill_md(key)
    missing = [e.name for e in exs if e.name not in text]
    assert not missing, f"rf-{key}: SKILL.md does not list examples {missing}"


EXAMPLE_PARAMS = [_param(k, k, e, id=f"{k}-{e.name}") for k in KEYS for e in examples(k)]


def _browser_initialized(spec) -> bool:
    """True when Browser's Node wrapper deps exist (``rfbrowser init``/``install`` ran)."""
    for location in spec.submodule_search_locations or ():
        if (Path(location) / "wrapper" / "node_modules").is_dir():
            return True
    return False


@pytest.mark.parametrize("key,example", EXAMPLE_PARAMS)
def test_examples_dryrun(key, example, tmp_path):
    pytest.importorskip("robot")
    spec = importlib.util.find_spec(LIBRARIES[key])
    if spec is None:
        pytest.skip(f"{LIBRARIES[key]} is not importable; dry run skipped (not passed)")
    if LIBRARIES[key] == "Browser" and not _browser_initialized(spec):
        pytest.skip("Browser installed without its Node dependencies (run `rfbrowser init` or "
                    "`rfbrowser install`); dry run skipped (not passed)")
    result = subprocess.run(
        [sys.executable, "-m", "robot", "--dryrun", "--output", "NONE", "--report", "NONE", "--log", "NONE",
         "--outputdir", str(tmp_path), str(example)],
        capture_output=True, text=True, timeout=180, cwd=example.parent,
    )
    out = result.stdout + result.stderr
    assert result.returncode == 0, out
    assert "[ ERROR ]" not in out, out
