"""Per-agent variants generated by scripts/build-agent-variants.py (marketplace-distribution).

Codex gets TOML subagents, OpenCode gets ``mode: subagent`` agents and a JS
plugin that runs the shared hook scripts. The variants are committed under
``plugins/rf-agentskills/variants/`` and must match the generator's output.
"""
from __future__ import annotations

import json
import shutil
import subprocess
import sys
import uuid
from pathlib import Path

import pytest

try:
    import tomllib
except ModuleNotFoundError:  # Python 3.10: the installer's tomli dependency
    import tomli as tomllib

ROOT = Path(__file__).resolve().parent.parent
PLUGIN = ROOT / "plugins" / "rf-agentskills"
VARIANTS = PLUGIN / "variants"
GENERATOR = ROOT / "scripts" / "build-agent-variants.py"
AGENTS = sorted((PLUGIN / "agents").glob("*.md"))
NODE = shutil.which("node")


def _body(md_text: str) -> str:
    end = md_text.index("\n---", 3)
    return md_text[end + 4:].lstrip("\n")


def _description(md_text: str) -> str:
    for line in md_text.splitlines()[1:]:
        if line.startswith("description:"):
            return line.split(":", 1)[1].strip().strip("\"'")
    raise AssertionError("no description")


@pytest.mark.parametrize("agent", AGENTS, ids=lambda p: p.stem)
def test_codex_toml_subagent(agent: Path) -> None:
    data = tomllib.loads((VARIANTS / "codex" / "agents" / f"{agent.stem}.toml").read_text(encoding="utf-8"))
    text = agent.read_text(encoding="utf-8")
    assert data["name"] == agent.stem
    assert data["description"] == _description(text)
    assert data["developer_instructions"].strip() == _body(text).strip()


@pytest.mark.parametrize("agent", AGENTS, ids=lambda p: p.stem)
def test_opencode_subagent(agent: Path) -> None:
    variant = (VARIANTS / "opencode" / "agents" / agent.name).read_text(encoding="utf-8")
    assert variant.startswith("---\n")
    front, rest = variant[4:].split("\n---\n", 1)
    meta = dict(line.split(": ", 1) for line in front.splitlines())
    assert meta["mode"] == "subagent"
    assert json.loads(meta["description"]) == _description(agent.read_text(encoding="utf-8"))
    body = rest.split("-->\n", 1)[1].lstrip("\n")  # after the generated-file note
    assert body == _body(agent.read_text(encoding="utf-8"))


def test_committed_variants_match_the_generator() -> None:
    res = subprocess.run([sys.executable, str(GENERATOR), "--check"], capture_output=True, text=True)
    assert res.returncode == 0, res.stderr


def test_generator_check_fails_after_a_hand_edit(tmp_path: Path) -> None:
    out = tmp_path / "plugin"
    subprocess.run([sys.executable, str(GENERATOR), "--out", str(out)], check=True, capture_output=True)
    edited = out / "variants" / "codex" / "agents" / "rf-debug-expert.toml"
    edited.write_text(edited.read_text(encoding="utf-8") + "\n# hand edit\n", encoding="utf-8")
    res = subprocess.run([sys.executable, str(GENERATOR), "--check", "--out", str(out)],
                         capture_output=True, text=True)
    assert res.returncode == 1 and "rf-debug-expert.toml" in res.stderr


def test_plugin_lists_unported_hooks() -> None:
    js = (VARIANTS / "opencode" / "plugins" / "rf-agentskills.js").read_text(encoding="utf-8")
    assert "UserPromptSubmit * -> maybe_inject_rf_context.mjs" in js
    assert 'const EDIT_SCRIPT = "validate_robot.mjs"' in js
    assert 'const SHELL_SCRIPT = "rf_error_hints.mjs"' in js
    assert 'const SESSION_SCRIPT = "check_rf_environment.mjs"' in js


# --- the OpenCode plugin, driven with stubbed OpenCode objects ---------------

def _module_importable(module: str) -> bool:
    return subprocess.run([sys.executable, "-c", f"import {module}"], capture_output=True).returncode == 0


def _install_layout(tmp_path: Path) -> Path:
    """<root>/plugins/rf-agentskills.js + <root>/rf-agentskills-files/scripts/ (installer layout)."""
    root = tmp_path / ".opencode"
    (root / "plugins").mkdir(parents=True)
    shutil.copy(VARIANTS / "opencode" / "plugins" / "rf-agentskills.js", root / "plugins" / "rf-agentskills.js")
    shutil.copytree(PLUGIN / "scripts", root / "rf-agentskills-files" / "scripts")
    return root / "plugins" / "rf-agentskills.js"


def _drive(plugin_js: Path, project: Path, steps: list[dict]) -> list[str]:
    """Call the plugin's hooks in order; return output.output after each tool call."""
    code = f"""
import {{ RfAgentSkills }} from {json.dumps(plugin_js.as_uri())};
const hooks = await RfAgentSkills({{ directory: {json.dumps(str(project))} }});
const steps = JSON.parse(process.argv[1]);
const outputs = [];
for (const s of steps) {{
  if (s.event) {{ await hooks.event({{ event: s.event }}); continue; }}
  const input = {{ tool: s.tool, sessionID: {json.dumps("S-" + uuid.uuid4().hex)}, callID: s.callID }};
  await hooks["tool.execute.before"](input, {{ args: s.args }});
  const output = {{ title: "", output: s.output ?? "", metadata: {{}} }};
  await hooks["tool.execute.after"](input, output);
  outputs.push(output.output);
}}
process.stdout.write(JSON.stringify(outputs));
"""
    res = subprocess.run([NODE, "--input-type=module", "-e", code, json.dumps(steps)],  # type: ignore[list-item]
                         capture_output=True, text=True, timeout=120, cwd=project)
    assert res.returncode == 0, res.stderr
    return json.loads(res.stdout)


@pytest.mark.skipif(NODE is None, reason="node not on PATH")
@pytest.mark.skipif(not _module_importable("robocop"), reason="Robocop not installed")
def test_opencode_plugin_appends_validation_errors(tmp_path: Path) -> None:
    plugin_js = _install_layout(tmp_path)
    broken = tmp_path / "tests" / "broken.robot"
    broken.parent.mkdir()
    broken.write_text("*** Test Cases ***\nT\n    FOR    ${x}    IN    a\n        Log    ${x}\n", encoding="utf-8")
    [out] = _drive(plugin_js, tmp_path, [
        {"tool": "write", "callID": "c1", "args": {"filePath": str(broken), "content": "..."}, "output": "Wrote file"},
    ])
    assert out.startswith("Wrote file") and "broken.robot" in out and "ERR" in out


@pytest.mark.skipif(NODE is None, reason="node not on PATH")
def test_opencode_plugin_bash_hints_and_quiet_tools(tmp_path: Path) -> None:
    plugin_js = _install_layout(tmp_path)
    outs = _drive(plugin_js, tmp_path, [
        {"tool": "bash", "callID": "c1", "args": {"command": "robot tests"},
         "output": "No keyword with name 'Foo' found."},
        {"tool": "read", "callID": "c2", "args": {"filePath": "x.robot"}, "output": "file text"},
    ])
    assert "rf-language" in outs[0]
    assert outs[1] == "file text"
