#!/usr/bin/env python3
"""Generate per-agent variants of the plugin's subagents and hooks.

Most agents read the Claude-format plugin as-is (marketplace-distribution D1).
Two need their own formats, generated from the canonical sources in
``plugins/rf-agentskills/`` (``agents/*.md``, ``hooks/hooks.json``):

* Codex:    ``variants/codex/agents/<name>.toml`` (name, description,
            developer_instructions) - Codex plugins cannot ship subagents.
* OpenCode: ``variants/opencode/agents/<name>.md`` (``mode: subagent``) and
            ``variants/opencode/plugins/rf-agentskills.js``, a JS plugin that
            runs the same hook scripts on OpenCode events.

Usage::

    python scripts/build-agent-variants.py            # write the variants
    python scripts/build-agent-variants.py --check    # exit 1 if they are stale
    python scripts/build-agent-variants.py --out DIR  # write into DIR instead

Stdlib only, so it runs on a bare Python in CI.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
PLUGIN = REPO / "plugins" / "rf-agentskills"
TEMPLATE = REPO / "scripts" / "templates" / "opencode-plugin.js"
GENERATED_NOTE = "Generated by scripts/build-agent-variants.py from plugins/rf-agentskills/{src}. Do not edit."

#: Canonical hook (event, script) -> OpenCode stand-in. Others are not ported.
OPENCODE_HOOKS = {
    ("PostToolUse", "validate_robot.mjs"): "edit",
    ("PostToolUse", "rf_error_hints.mjs"): "shell",
    ("SessionStart", "check_rf_environment.mjs"): "session",
}
_SCRIPT_RE = re.compile(r"scripts/([A-Za-z0-9_.-]+\.mjs)")


def _frontmatter(text: str) -> tuple[dict[str, str], str]:
    """Top-level ``key: value`` pairs of a simple YAML frontmatter, and the body."""
    if not text.startswith("---"):
        raise ValueError("missing frontmatter")
    end = text.index("\n---", 3)
    meta: dict[str, str] = {}
    for line in text[3:end].strip().splitlines():
        if ":" in line and not line.startswith((" ", "\t")):
            key, value = line.split(":", 1)
            meta[key.strip()] = value.strip().strip("\"'")
    return meta, text[end + 4:].lstrip("\n")


def _toml_basic(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)  # a JSON string is a valid TOML basic string


def _toml_multiline(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"""', '""\\"')
    return f'"""\n{escaped}"""'


def codex_agent(md: Path) -> str:
    meta, body = _frontmatter(md.read_text(encoding="utf-8"))
    return (
        f"# {GENERATED_NOTE.format(src='agents/' + md.name)}\n"
        f"name = {_toml_basic(meta['name'])}\n"
        f"description = {_toml_basic(meta['description'])}\n"
        f"developer_instructions = {_toml_multiline(body)}\n"
    )


def opencode_agent(md: Path) -> str:
    meta, body = _frontmatter(md.read_text(encoding="utf-8"))
    return (
        "---\n"
        f"description: {json.dumps(meta['description'], ensure_ascii=False)}\n"
        "mode: subagent\n"
        "---\n"
        f"<!-- {GENERATED_NOTE.format(src='agents/' + md.name)} -->\n\n"
        f"{body}"
    )


def opencode_plugin(hooks_json: Path) -> str:
    hooks = json.loads(hooks_json.read_text(encoding="utf-8"))["hooks"]
    ported: dict[str, str] = {}
    not_ported: list[str] = []
    for event, groups in hooks.items():
        for group in groups:
            for handler in group.get("hooks", []):
                m = _SCRIPT_RE.search(handler.get("command", ""))
                if not m:
                    continue
                target = OPENCODE_HOOKS.get((event, m.group(1)))
                label = f"{event} {group.get('matcher') or '*'} -> {m.group(1)}"
                if target:
                    ported[target] = m.group(1)
                else:
                    not_ported.append(label)
    template = TEMPLATE.read_text(encoding="utf-8")
    return (
        template.replace("__GENERATED_NOTE__", GENERATED_NOTE.format(src="hooks/hooks.json"))
        .replace("__EDIT_SCRIPT__", ported.get("edit", ""))
        .replace("__SHELL_SCRIPT__", ported.get("shell", ""))
        .replace("__SESSION_SCRIPT__", ported.get("session", ""))
        .replace("__NOT_PORTED__", "\n".join(f"//   {x}" for x in sorted(not_ported)) or "//   (none)")
    )


def build(plugin: Path) -> dict[str, str]:
    """Relative path under ``plugin`` -> file content."""
    out: dict[str, str] = {}
    for md in sorted((plugin / "agents").glob("*.md")):
        out[f"variants/codex/agents/{md.stem}.toml"] = codex_agent(md)
        out[f"variants/opencode/agents/{md.name}"] = opencode_agent(md)
    out["variants/opencode/plugins/rf-agentskills.js"] = opencode_plugin(plugin / "hooks" / "hooks.json")
    return out


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail if committed variants are stale")
    parser.add_argument("--out", type=Path, help="write the variants under this directory")
    args = parser.parse_args(argv)
    files = build(PLUGIN)
    target = args.out or PLUGIN
    if args.check:
        stale = [rel for rel, text in files.items()
                 if not (target / rel).is_file() or (target / rel).read_text(encoding="utf-8") != text]
        existing = {p.relative_to(target).as_posix() for p in (target / "variants").rglob("*") if p.is_file()}
        extra = sorted(existing - set(files))
        for rel in stale:
            print(f"stale: {rel}", file=sys.stderr)
        for rel in extra:
            print(f"orphan: {rel}", file=sys.stderr)
        if stale or extra:
            print("Run: python scripts/build-agent-variants.py", file=sys.stderr)
            return 1
        print(f"{len(files)} variant files up to date")
        return 0
    variants = target / "variants"
    for old in sorted(variants.rglob("*"), reverse=True) if variants.exists() else []:
        if old.is_file() and old.relative_to(target).as_posix() not in files:
            old.unlink()
    for rel, text in files.items():
        path = target / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
    print(f"{len(files)} variant files written to {variants}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
